### ISSUE TITLE
Remove dependency on Nodejs for 'fs'

### ISSUE THREAD

**Issue by PizzaConsole** [p-kuen/pdf-lib-builder#1]
Hi, amazing library that you have wrote here!!

`import {readFileSync} from 'fs'`
will prevent a user from deploying this to a service like Cloudflare workers. I think it would good to remove the dependency and jut have the function on accept a type of  `PDFImage`

**Comment by p-kuen** [comment]
Thanks, this was a good hint. `fs` dependency should not be part of this package. I just released v3.0.0 where this is not a dependency anymore.
