### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by PizzaConsole** [p-kuen/pdf-lib-builder#6]
hello, looks like there is a regression bug with the 3.0.0 update.
This happens with passing a PDFImage into the image function like in the example.

**Comment by p-kuen** [comment]
Hey, thanks for all your help.
You run the package not on nodejs, right?

**Comment by PizzaConsole** [comment]
I use Nuxt3 to run in the browser. Which means it cannot use `Buffer`
